spring.datasource.url=jdbc:mysql://localhost:3306/sucursal_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs
